apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: university-dtg
  annotations:
    fluxcd.io/automated: "false"
  namespace: university-ns
spec:
  releaseName: university-dtg
  chart:
    path: platforms/hyperledger-indy/charts/indy-domain-genesis
    git: https://github.com/sauveergoel/blockchain-automation-framework.git
    ref: indydemo
  values:
    metadata:
      name: university-dtg
      namespace: university-ns
    organization:
      name: university
    configmap:
      domainGenesis: |-
        {"reqSignature":{},"txn":{"data":{"alias":"authority-trustee","dest":"Nzw1QcpbASujUP1pi1qxgV","role":"0","verkey":"CzRhZ3Nq5C8AimtySeXbwCKCCfaaj9JYPHH7y7GDK9tA"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":1},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-trustee","dest":"So7jbcrXkJyjABB2qJ7z8","role":"0","verkey":"F4SBRU4o9aGgfHgiC246FYUQxeQEvnsbvKHsHDd7Cwp"},"metadata":{"from":"Nzw1QcpbASujUP1pi1qxgV"},"type":"1"},"txnMetadata":{"seqNo":2},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-1","dest":"KcNW29JHkjqJAX9Bmvprv2","role":"2","verkey":"B9J34ZgzZqB1KLtaXtSNa7W4BmesYm5R849k3sMKZviG"},"metadata":{"from":"So7jbcrXkJyjABB2qJ7z8"},"type":"1"},"txnMetadata":{"seqNo":3},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-2","dest":"8rkktMrLJveYAgCkyyKs4A","role":"2","verkey":"5HQJAD45DBgpFFCKJvYormDXzjGgniqpMgSnPiK6kYmh"},"metadata":{"from":"So7jbcrXkJyjABB2qJ7z8"},"type":"1"},"txnMetadata":{"seqNo":4},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"employer-trustee","dest":"VSg7z8PeLdP8FA8yogM2ih","role":"0","verkey":"GW8Tqo4R9JyaKMeLtJXChGJE9C7XNVH9MXspFYy4J4pB"},"metadata":{"from":"Nzw1QcpbASujUP1pi1qxgV"},"type":"1"},"txnMetadata":{"seqNo":5},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"employer-steward-1","dest":"QfRcWWsbkKUhbzocXjS92","role":"2","verkey":"Du23H1C2vt5s6tKpqDkiJQcDZRhn8oJbYbYnsE5F1hZ"},"metadata":{"from":"VSg7z8PeLdP8FA8yogM2ih"},"type":"1"},"txnMetadata":{"seqNo":6},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"employer-steward-2","dest":"niuNn4JY8bM31abenmYhP","role":"2","verkey":"RvNtBujiJrgi8QqnqaaTLYQuFwAMJixTPXMeCW3brzK"},"metadata":{"from":"VSg7z8PeLdP8FA8yogM2ih"},"type":"1"},"txnMetadata":{"seqNo":7},"ver":"1"}
