apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: university-dtg
  annotations:
    fluxcd.io/automated: "false"
  namespace: university-ns
spec:
  releaseName: university-dtg
  chart:
    path: platforms/hyperledger-indy/charts/indy-domain-genesis
    git: https://github.com/sauveergoel/blockchain-automation-framework.git
    ref: indydemo
  values:
    metadata:
      name: university-dtg
      namespace: university-ns
    organization:
      name: university
    configmap:
      domainGenesis: |-
        {"reqSignature":{},"txn":{"data":{"alias":"authority-trustee","dest":"GWADCwFSZjjTZzovQZq4ao","role":"0","verkey":"9T5BaCNsTy6rdnmoJm1EPuf3emmFxMJUBqia41y6CGGN"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":1},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-trustee","dest":"Wnp4QSw2zgh4Rifmx3Dkrs","role":"0","verkey":"HEiXLxDnM7CbgymA6SSBZs237mQSqEYV1CdDHAjkXjPw"},"metadata":{"from":"GWADCwFSZjjTZzovQZq4ao"},"type":"1"},"txnMetadata":{"seqNo":2},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-1","dest":"K4SUQnj3EZJ4Pc9tHcF1RW","role":"2","verkey":"AqtcpAVZ5VasCgzpFdYQVaupPW4opkiNKKtTGcQXKEhc"},"metadata":{"from":"Wnp4QSw2zgh4Rifmx3Dkrs"},"type":"1"},"txnMetadata":{"seqNo":3},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-2","dest":"GigGhZ3ZrnsNecwFPkAakV","role":"2","verkey":"9ZtumXC6vD824SDK5FPPYRqAgKkHY113hUY4szLEpmw5"},"metadata":{"from":"Wnp4QSw2zgh4Rifmx3Dkrs"},"type":"1"},"txnMetadata":{"seqNo":4},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"employer-trustee","dest":"QuCrKqubGGy2cHHSTWnCNB","role":"0","verkey":"E2XemjUhKCHYU87R11nHEqV5H9ShFmT8X9qpbEFFfsGR"},"metadata":{"from":"GWADCwFSZjjTZzovQZq4ao"},"type":"1"},"txnMetadata":{"seqNo":5},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"employer-steward-1","dest":"3Q5CuvDxL8pimsbax1ptsQ","role":"2","verkey":"2JoMevZTjAXaqLjE6uFPKDkm5VksXtk5Gnm2fPmP4oMa"},"metadata":{"from":"QuCrKqubGGy2cHHSTWnCNB"},"type":"1"},"txnMetadata":{"seqNo":6},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"employer-steward-2","dest":"Ly3wpsXtNuZDyWk8XVrrAy","role":"2","verkey":"BtBGZ1PVzd4LX37u4BskTjQpMEXj9eqcwjjqDMg8UqKB"},"metadata":{"from":"QuCrKqubGGy2cHHSTWnCNB"},"type":"1"},"txnMetadata":{"seqNo":7},"ver":"1"}
