apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: employer-employer-endorser-transaction
  annotations:
    fluxcd.io/automated: "false"
  namespace: employer-ns
spec:
  releaseName: employer-employer-endorser-transaction
  chart:
    path: platforms/hyperledger-indy/charts/indy-ledger-txn
    git: https://github.com/sauveergoel/blockchain-automation-framework.git
    ref: indydemo
  values:
    metadata:
      name: employer-employer-endorser-transaction
      namespace: employer-ns
    network:
      name: baf
    genesis:
      pool: Z2VuZXNpcy9wb29sX3RyYW5zYWN0aW9uc19nZW5lc2lz
      domain: ZG9tYWluL2RvbWFpbl90cmFuc2FjdGlvbnNfZ2VuZXNpcw==
      add_org: False
    image:
      cli:
        name: employer
        repository: index.docker.io/hyperledgerlabs/indy-ledger-txn:latest
        pullSecret: regcred
    vault:
      address: http://vault.internal.demo.aws.blockchaincloudpoc.com:9001
      role: rw
      serviceAccountName: employer-admin-vault-auth
      auth_path: kubernetes-employer-admin-auth
    organization:
      name: employer
      adminIdentity:
        name: authority-trustee
        did: GWADCwFSZjjTZzovQZq4ao
        path: authority/trustees
      newIdentity:
        name: employer-endorser
        role: ENDORSER
        did: 9yq2HHd8Y8Hbton1frgSPh
        verkey: 5tsQ8XQNA65hJkmeyd4HsNwNfcg1ZuP5QfonKdQ4qvqu
        path: employer/endorsers
    node:
      name: employer
