apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: storelstorelibft
  namespace: storel-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: storelstorelibft
  chart:
    git: ssh://git@github.com/sauveergoel/blockchain-automation-framework.git
    ref: besuupgrade
    path: platforms/hyperledger-besu/charts/node_orion 
  values:
    replicaCount: 1

    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5

    staticnodes:
      - "enode://04e92d82c8cc1b68a0370ee610608cbaaa591212e41c798e13352f556e9ad3bd84f4e5d5fb35d3abe4082d3783a5854de68b1e5e6d959f2ce69e132d11df2863@54.73.71.70:15050"
      - "enode://4e54f2464caaac5f3ba46a1286ade6c8948597a5e1c02686ded791c8c9f6cd6cf638133a10f47f808d88c3842c02bb0bc3b1ac37c50e00c65edda3a35f927cb9@54.73.71.70:15060"
      - "enode://53cc86cd1e95ba99f88dce590594dec1a7673bf0e1b7ba5264d4611988610cb5b9020b77219313247bfab1a2a214d2e696c2992da810c1252de612a589134829@54.73.71.70:15070"
      - "enode://7c38993dd7d76da2445178fae6d7311013941680493c86a6322fc551e85acae38d2247c6f292e37650609ecaedcc73fbeacc05882cab05a27870581e1ead4e9d@54.73.71.70:15080"
      - "enode://da0f12ee9adfc5f75ae7ff85f5aa02881c68c1f214729e019c1e01e22625db364804c7c45a4e2c4e54383d7b76515eab30d56d9d8ea5c4f470666817f9f7a885@54.73.71.70:15010"
      - "enode://dac1092b7b83249af4f44cec2139cb74b48611e4e640b5b7f78c263567d1aeda37fe974e0688495a14aaedc1c5b71c640da2832ad069cd27d1448be6bbf99463@54.73.71.70:15020"
      - "enode://005feca39dfb36e3a860f4435f19f274469c7d3bf4ce57116adcdb0eff9ea8a2936da6d90c23e4a2da931598ed5022525cfa2d3d6ef60b9571581c97dc93dd43@54.73.71.70:15030"
      - "enode://20fba06608e431c1b62c4437ed0adbbd631b7a649b8cddd1024197e38ed3030bcda4b087e91254dbcd499140d244f77d4e74b17787a8ac6e1cb93b2532930925@54.73.71.70:15040"

    metadata:
      namespace: storel-bes
      labels:

    liveliness_check:
      enabled: false

    proxy:
      provider: ambassador
      external_url: storel.besu.devh3.aws.blockchaincloudpoc-develop.com
      p2p: 15030
      rpc: 15031
      tmport: 15033

    images:
      node: hyperledger/besu:1.4.4
      alpineutils: hyperledgerlabs/alpine-utils:1.0
      orion: pegasyseng/orion:1.5.2

    node:
      name: storel
      consensus: ibft
      subject: O=Store,OU=Store,L=New York,C=US
      mountPath: /etc/genesis
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

    orion:
      name: orion
      tls: True
      confdir: /etc/config
      url: "https://storel.besu.devh3.aws.blockchaincloudpoc-develop.com"
      nodelist: "\"https://carrierl.besu.devh3.aws.blockchaincloudpoc-develop.com:15013\",\"https://manufacturerl.besu.devh3.aws.blockchaincloudpoc-develop.com:15023\",\"https://warehousel.besu.devh3.aws.blockchaincloudpoc-develop.com:15043\""
      trust: ca-or-tofu
      ports:
        nodeport: 8888
        clientport: 8080

    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi

    vault:
      address: http://ab0e697583dfc447b8d14e6526e14759-1481581572.eu-west-1.elb.amazonaws.com:20002
      secretprefix: secret/storel-bes/crypto/storel
      serviceaccountname: vault-auth
      keyname: data
      oriondir: orion
      tlsdir: tls
      role: vault-role
      authpath: besustorel

    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDIwMTgsCiAgICAiY29uc3RhbnRpbm9wbGVmaXhibG9jayI6IDAsCiAgICAiY29udHJhY3RTaXplTGltaXQiOiAyMTQ3NDgzNjQ3LAogICAgImliZnQyIjogewogICAgICAiYmxvY2twZXJpb2RzZWNvbmRzIjogMiwKICAgICAgImVwb2NobGVuZ3RoIjogMzAwMDAsCiAgICAgICJyZXF1ZXN0dGltZW91dHNlY29uZHMiOiAxMAogICAgfQogIH0sCiAgIm5vbmNlIjogIjB4MCIsCiAgInRpbWVzdGFtcCI6ICIweDU4ZWU0MGJhIiwKICAiZ2FzTGltaXQiOiAiMHgxZmZmZmZmZmZmZmZmZiIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAiZXh0cmFEYXRhIjogIjB4Zjg3ZWEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGY4NTQ5NDc4OWMwN2QwYTdlOTUzZjEwMzNiZjA4ODkyYTg2ZWY4OWQ1MzY5Y2E5NDFkYTU3ZDcwMmI4NjVkZWYzYjRmMzAwYmE0ODVhYjNjZTVkYWMwZGI5NDEyMTJkNWY4NTRlYmIzOGM0Y2IzMzA5ZWFiZWZjNTYxYzlkNjdmM2Q5NDRhNTA1ZGJkZjcwMmI1M2E5MzQzMmE0NzExOTYxZjI1OTg5M2NjYjQ4MDg0MDAwMDAwMDBjMCIKfQ==
