apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: authority-authority-trustee
  annotations:
    fluxcd.io/automated: "false"
  namespace: authority-ns
spec:
  releaseName: authority-authority-trustee
  chart:
    path: platforms/hyperledger-indy/charts/indy-key-mgmt
    git: https://github.com/sauveergoel/blockchain-automation-framework.git
    ref: indydemo
  values:
    metadata:
      name: authority-authority-trustee
      namespace: authority-ns
    network:
      name: baf
    image:
      name: authority
      repository: index.docker.io/hyperledgerlabs/indy-key-mgmt:1.11.0
      pullSecret: regcred
    vault:
      address: http://vault.internal.demo.aws.blockchaincloudpoc.com:9001
      keyPath: authority.trustees
      identity: authority-trustee
      auth_path: kubernetes-authority-admin-auth
    account:
      service: authority-admin-vault-auth
      role: rw
