apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: bank-dtg
  annotations:
    fluxcd.io/automated: "false"
  namespace: bank-ns
spec:
  releaseName: bank-dtg
  chart:
    path: platforms/hyperledger-indy/charts/indy-domain-genesis
    git: https://github.com/sauveergoel/blockchain-automation-framework.git
    ref: indydemo
  values:
    metadata:
      name: bank-dtg
      namespace: bank-ns
    organization:
      name: bank
    configmap:
      domainGenesis: |-
        {"reqSignature":{},"txn":{"data":{"alias":"bank-trustee","dest":"3U7i2TDdkRhiihPZhK11nS","role":"0","verkey":"2M1AiuecxEeLtkh8h1pbai8sC1yyVvFiVjGq9ZabMtbX"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":1},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"bank-steward-1","dest":"Fxhpz9SaHG4EpykEixpNza","role":"2","verkey":"99vqE5vtPdK4hoGZGFhb4BCTQc8DmoT54GDo71FtCwDQ"},"metadata":{"from":"3U7i2TDdkRhiihPZhK11nS"},"type":"1"},"txnMetadata":{"seqNo":2},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"bank-steward-2","dest":"CVJ9xnXFwUe2TmZVs2kizu","role":"2","verkey":"7G9vX5zMxYi6Uaz4HUaR6WZNHjbScYawrncoijjWTRLE"},"metadata":{"from":"3U7i2TDdkRhiihPZhK11nS"},"type":"1"},"txnMetadata":{"seqNo":3},"ver":"1"}
