apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: university-endorser
  annotations:
    fluxcd.io/automated: "false"
  namespace: university-ns
spec:
  releaseName: university-endorser-faber
  chart:
    path: examples/identity-app/charts/faber
    git: https://github.com/sauveergoel/blockchain-automation-framework.git
    ref: indydemo
  values:
    metadata:
      namespace: university-ns
      name: university-endorser
    organization:
      name: university
    image:
      pullSecret: regcred
      init:
        name: certs-init
        repository: alpine:3.9.4
      agent:
        name: university-endorser
        repository: index.docker.io/sownak/aries-agents:1.11.0
    service:
      ports: 
        service: 15023
        endpoint: 15024
      
      address: university-endorser.indy.demo.aws.blockchaincloudpoc.com
      
      ledger: http://authority-webserver.indy.demo.aws.blockchaincloudpoc.com:15010
      genesis: http://authority-webserver.indy.demo.aws.blockchaincloudpoc.com:15010/genesis
    vault:
      address: http://vault.internal.demo.aws.blockchaincloudpoc.com:9001
      serviceAccountName: university-university-endorser-vault-auth
      authPath: kubernetes-university-university-endorser-auth
      endorserName: university-endorser
      role: ro
    storage:
      size: 128Mi
      className: university-aws-storageclass
    proxy:
      
      provider: "ambassador"
